### ISSUE TITLE
Issue with connectwise module

### ISSUE THREAD

**Issue by IanRVic** [FreePBX/superfecta#219]
Hi,

Connectwise module has 3 places with the line:

``` php
$url="https://$integration_site/v4_6_release/services/system_io/integration_io.asmx/ProcessClientAction?actionString=".urlencode($integration_xml);
```

problem is - with connectwise - every time they do a new release, they change the first directory

code has `/v4_6_release/`

current is `/v2014_4/`

would it be possible to change the code so that the release version of connectwise is a field to fill in within superfecta's web interface - so that when updates to either the superfecta version or connectwise happen we can stay updated.

Would insert/propose change to code myself but not quite sure how to and want to respect the process.

Thanks

Ian

**Comment by madjeff** [comment]
We are a connectwise/freepbx shop and I'm trying to Connectwise integrated with our FreePBX system. However, the page:

http://wiki.manageditby.us/2013/08/18/use-connectwise-api-as-caller-id-source-in-asterisk-pbx/

seem to be offline so I am shooting in the dark on how to set this up. Does anyone have a step by step. I'm assuming I need to setup an Integrator login, using the settings examples above?

**Comment by madjeff** [comment]
Never mind, got it sorted out. Created a new integrator login, setup as above and it worked great.
