### ISSUE TITLE
In FreePBX-17 Add the Allowlist as a lookup source in CID Superfecta. 

### ISSUE THREAD

**Issue by kennesaw10** [FreePBX/superfecta#351]
### FreePBX Version

FreePBX 17

### Feature Description

Since the phonebook module is not included in FreePBX-17, we need the allowlist to be a lookup source in the CID Superfecta module.  Many people currently populate the phonebook database and use if for CID Superfecta lookups so to provide equivalent functionality in FreePBX-17, the alllowlist data needs to be available to Superfecta lookups.

**Comment by lgaetz** [comment]
Hi Ken, got a working source up on a PR now
https://github.com/FreePBX/superfecta/pull/352

**Comment by kennesaw10** [comment]
> Hi Ken, got a working source up on a PR now #352

Thank you very much.  Hopefully, this will also feed into FreePBX-17?
